### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by SpaghetCat** [Gavin132/pog#1]
Beste examenkandidaten havo en vwo,

We komen nu echt heel dicht bij het eindexamen en moeten  de laatste puntjes op de i gaan zetten. Daarvoor is er op donderdag om 12.35 uur een exameninstructie. Het is noodzakelijk dat je deze instructie op school bijwoont, omdat je daar je definitieve SE lijst ontvangt. Daarnaast ontvang je de indeling van het examen, waar en wanneer je verwacht wordt en krijg je de laatste mogelijkheid om eventuele wijzigingen kenbaar te maken.
Je zult op donderdag bij je mentor worden ingedeeld tijdens het derde blok, deze zal je de benodigde papieren overhandigen en vanuit het examenbureau wordt er een presentatie gedeeld op de schermen.
Deze presentatie duurt circa 60 minuten

Controleren
Wil je vast controleren op SOM of al je cijfer (goed) staan ingevoerd. De cijfers van de Beco inhaaltoetsen en herkansingen van dinsdag verwacht ik in de loop van die dag. Ook is het belangrijk dat de juiste titel bij je profielwerkstuk is genoteerd.
Controleer ook vast je persoonlijke gegevens, alsmede het telefoonnummer waarop je te bereiken bent. Dat hebben we straks nodig op de uitslagmomenten.
Mocht je iets tegenkomen dat niet klopt, kom dan langs het Examenbureau. Klopt er iets niet met de persoonsgegevens, dan ga je langs mevrouw Bakkenes op de administratie.

Voor nu wensen we je fijns en gezegende paasdagen,

N.Y. Leeuwenburg
W.M. Korbijn
R de Knegt

**Comment by Gavin132** [comment]
dankjewel spagwr
